name: Keep GitHub actions alive despite inactivity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  call-enable:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: actions-keepalive
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: ./enable_workflows.py
